//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSearchEngine.Web {
    
    
    public partial class ProductDetail {
        
        /// <summary>
        /// ProductRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater ProductRepeater;
        
        /// <summary>
        /// BaseCategoryListUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.Web.Control.BaseCategoryList BaseCategoryListUserControl;
        
        /// <summary>
        /// BrandListtUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.Web.Control.BrandList BrandListtUserControl;
        
        /// <summary>
        /// SpecialProductListUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.Web.Control.SpecialProductList SpecialProductListUserControl;
        
        /// <summary>
        /// LastAddedProductsUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.Web.Control.LastAddedProducts LastAddedProductsUserControl;
    }
}
