//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSearchEngine.CMS {
    
    
    public partial class DashBoard {
        
        /// <summary>
        /// NavigationImageListUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.CMS.Control.NavigationImageList NavigationImageListUserControl;
        
        /// <summary>
        /// OverViewListUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.CMS.Control.OverViewList OverViewListUserControl;
        
        /// <summary>
        /// Last10AddedProductsUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.CMS.Control.Last10AddedProducts Last10AddedProductsUserControl;
        
        /// <summary>
        /// Last5AddedProductsUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.CMS.Control.Last5AddedProducts Last5AddedProductsUserControl;
        
        /// <summary>
        /// StoreInformationUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.CMS.Control.StoreInformation StoreInformationUserControl;
        
        /// <summary>
        /// StoreListUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProductSearchEngine.CMS.Control.StoreList StoreListUserControl;
    }
}
